{% set name = "climpred" %}
{% set version = "2.4.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 345d84fb9bce4275deb613725e3451fd7205712edca7cd01f0175460fad6f7a5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - python >3.8
    - pip
    - setuptools_scm
    - setuptools_scm_git_archive
  run:
    - python >3.8
    - bias_correction >=0.4
    - bottleneck
    - cf_xarray >=0.6.0
    - cftime >=1.5.0
    - dask-core >=2021.10.0
    - eofs
    - netcdf4
    - matplotlib-base
    - nc-time-axis >=1.4.0
    - numba >=0.52
    - numpy
    - pandas
    - pooch >=1.4
    - scipy
    - xarray
    - xclim >=0.46
    - xesmf
    - xrft
    - xskillscore >=0.0.20

test:
  requires:
    - pip
  imports:
    - climpred
  commands:
    - pip check

about:
  home: http://github.com/pangeo-data/climpred
  license: MIT
  license_file: LICENSE.txt
  summary: Verification of weather and climate forecasts
  doc_url: http://climpred.readthedocs.io
  dev_url: https://github.com/pangeo-data/climpred

extra:
  recipe-maintainers:
    - zeitsperre
    - bradyrx
    - aaronspring
    - ahuang11
    - Zeitsperre
