{% set name = "climpred" %}
{% set version = "2.5.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0948dc72beac30bdf782e123a391db46e7472ed2cf151afc8e8c6c980151fc44

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - python >3.9
    - pip
    - setuptools >=64.0
    - setuptools_scm >=8.0
    - wheel
  run:
    - python >3.9
    - bias_correction >=0.4
    - bottleneck
    - cftime >=1.5.0
    - cf_xarray >=0.6.0
    - dask-core >=2021.10.0
    - eofs
    - matplotlib-base
    - nc-time-axis >=1.4.0
    - numba >=0.52
    - numpy >=1.25.0,<2.0.0
    - packaging
    - pooch >=1.4
    - scipy >=1.2
    - toolz
    - xarray >=2022.06.0
    - xclim >=0.46
    - xesmf
    - xrft
    - xskillscore >=0.0.20

test:
  requires:
    - pip
  imports:
    - climpred
  commands:
    - pip check

about:
  home: http://github.com/pangeo-data/climpred
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  license_url: https://github.com/pangeo-data/climpred/blob/main/LICENSE.txt
  summary: Verification of weather and climate forecasts
  dev_url: https://github.com/pangeo-data/climpred
  doc_url: http://climpred.readthedocs.io/en/stable/
  doc_source_url: https://github.com/pangeo-data/climpred/blob/main/README.rst

extra:
  recipe-maintainers:
    - zeitsperre
    - bradyrx
    - aaronspring
    - ahuang11
