{% set name = "climpred" %}
{% set version = "2.1.5.post1" %}


package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ba2ae18d12ccc0593d8f8d58f199d644ff70585fa07f7e06333c629e77f1f845

build:
  number: 0 
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - python >3.6
    - pip
    - setuptools_scm
    - setuptools_scm_git_archive
  run:
    - python >3.6
    - cftime >=1.1.2
    - eofs
    - ipython
    - matplotlib-base
    - numpy
    - pandas
    - scipy
    - toolz
    - xarray >=0.16.1
    - xrft
    - dask !=2021.03.0
    - xskillscore >=0.0.20
    - netcdf4
    - nc-time-axis
    - bias_correction

test:
  imports:
    - climpred

about:
  home: http://github.com/pangeo-data/climpred
  license: MIT
  license_file: LICENSE.txt
  summary: Verification of weather and climate forecasts
  doc_url: http://climpred.readthedocs.io/
  dev_url: https://github.com/pangeo-data/climpred

extra:
  recipe-maintainers:
    - bradyrx
    - aaronspring
    - ahuang11
