{% set name = "climpred" %}
{% set version = "2.3.1" %}


package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a08ac1e37adaa56564b3c9dba9fee0ff319aa76d55e062b972599193554c1867

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - python >3.5
    - pip
    - setuptools_scm
    - setuptools_scm_git_archive
  run:
    - python >3.5
    - cftime >=1.1.2
    - eofs
    - esmtools >=1.1.3
    - ipython
    - matplotlib-base
    - numpy
    - pandas
    - scipy
    - toolz
    - xarray >=0.16.1
    - xrft
    - xskillscore >=0.0.18
    - netcdf4
    - nc-time-axis

test:
  imports:
    - climpred

about:
  home: http://github.com/pangeo-data/climpred
  license: MIT
  license_file: LICENSE.txt
  summary: Verification of weather and climate forecasts
  doc_url: http://climpred.readthedocs.io/
  dev_url: https://github.com/pangeo-data/climpred

extra:
  recipe-maintainers:
    - bradyrx
    - aaronspring
    - rabernat
    - ahuang11
    - dougiesquire
    - raybellwaves
    - kpegion
